In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time

service = Service(executable_path=ChromeDriverManager().install())
options = Options()
driver = webdriver.Chrome(service=service, options=options)

In [2]:
driver.get("https://www.goodreads.com/list/show/19.Best_for_Book_Clubs")

In [6]:
driver.find_element(By.XPATH, "//span[@class='smallText uitext']/a[2]").text

'2,254 people voted'

In [ ]:
/html/body/div[2]/div[3]/div[1]/div[2]/div[3]/div[5]/table/tbody/tr[2]/td[3]/div[2]/span/a[1]

In [ ]:
#all_votes > table > tbody > tr:nth-child(2) > td:nth-child(3) > div:nth-child(7) > span > a:nth-child(1)

In [1]:
import pandas as pd

In [2]:
colums = ['bookUrl', 'number', 'bookname', 'author', 'prices', 'describe', 'rating', 'ratingcount', 'reviews', 'fivestars', 'fourstars', 'threestars', 'twostars', 'onestar', 'pages', 'publish', 'authorUrl', 'genre', 'score', 'votes']

In [3]:
df = pd.DataFrame(columns=colums)

In [4]:
df

Empty DataFrame
Columns: [bookUrl, number, bookname, author, prices, describe, rating, ratingcount, reviews, fivestars, fourstars, threestars, twostars, onestar, pages, publish, authorUrl, genre, score, votes]
Index: []

In [12]:
df = pd.read_csv('csvdataunitop.csv', delimiter='$', names=colums)

In [13]:
df

,bookUrl,number,bookname,author,prices,describe,rating,ratingcount,reviews,fivestars,fourstars,threestars,twostars,onestar,pages,publish,authorUrl,genre,score,votes
0,https://www.goodreads.com/book/show/4667024-th...,1,The Help,Kathryn Stockett,Kindle $14.99,Three ordinary women are about to take one ext...,4.47,"2,848,844","91,733","1,728,306 (60%)","816,954 (28%)","231,931 (8%)","45,239 (1%)","26,414 (<1%)","464 pages, Hardcover","First published February 10, 2009",https://www.goodreads.com/author/show/1943477....,['Fiction'],"score: 220,911","2,254 people voted"
1,https://www.goodreads.com/book/show/43641.Wate...,3,Water for Elephants,Sara Gruen,Kindle Unlimited $0.00,"When Jacob Jankowski, recently orphaned and su...",4.11,"1,645,651","63,532","665,932 (40%)","607,586 (36%)","282,262 (17%)","66,942 (4%)","22,929 (1%)","368 pages, Paperback","First published May 22, 2006",https://www.goodreads.com/author/show/24556.Sa...,['Fiction'],"score: 161,351","1,651 people voted"
2,https://www.goodreads.com/book/show/77203.The_...,2,The Kite Runner,Khaled Hosseini,Kindle $13.99,1970s Afghanistan: Twelve-year-old Amir is des...,4.35,"3,247,847","102,520","1,774,028 (54%)","1,006,502 (30%)","333,826 (10%)","85,539 (2%)","47,952 (1%)","371 pages, Paperback","First published May 29, 2003",https://www.goodreads.com/author/show/569.Khal...,['Fiction'],"score: 168,222","1,716 people voted"
3,https://www.goodreads.com/book/show/2657.To_Ki...,5,To Kill a Mockingbird,Harper Lee,Shop this series,The unforgettable novel of a childhood in a sl...,4.26,"6,360,272","121,822","3,284,266 (51%)","1,900,179 (29%)","838,422 (13%)","220,580 (3%)","116,825 (1%)","323 pages, Paperback","First published July 11, 1960",https://www.goodreads.com/author/show/1825.Har...,['Fiction'],"score: 120,239","1,252 people voted"
4,https://www.goodreads.com/book/show/19063.The_...,4,The Book Thief,Markus Zusak,Kindle $10.99,Librarian's note: An alternate cover edition c...,4.39,"2,660,441","149,710","1,543,905 (58%)","747,818 (28%)","261,916 (9%)","72,444 (2%)","34,358 (1%)","592 pages, Kindle Edition","First published September 1, 2005",https://www.goodreads.com/author/show/11466.Ma...,['Historical Fiction'],"score: 132,988","1,365 people voted"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194,https://www.goodreads.com/book/show/61439040-1984,21,1984,George Orwell,Kindle Unlimited $0.00,A masterpiece of rebellion and imprisonment wh...,4.19,"4,835,356","125,903","2,283,297 (47%)","1,583,479 (32%)","686,543 (14%)","183,882 (3%)","98,155 (2%)","368 pages, Paperback","First published June 8, 1949",https://www.goodreads.com/author/show/3706.Geo...,['Classics'],"score: 53,220",577 people voted
1195,https://www.goodreads.com/book/show/2429135.Th...,20,The Girl with the Dragon Tattoo,Stieg Larsson,Shop this series,"Harriet Vanger, a scion of one of Sweden’s wea...",4.17,"3,264,698","79,635","1,523,460 (46%)","1,080,337 (33%)","442,802 (13%)","128,470 (3%)","89,629 (2%)","480 pages, Hardcover","First published August 1, 2005",https://www.goodreads.com/author/show/706255.S...,['Fiction'],"score: 54,721",598 people voted
1196,https://www.goodreads.com/book/show/1618.The_C...,19,The Curious Incident of the Dog in the Night-Time,Mark Haddon,Kindle $12.99,Christopher John Francis Boone knows all the c...,3.89,"1,515,303","57,535","461,230 (30%)","581,227 (38%)","347,894 (22%)","91,099 (6%)","33,853 (2%)","226 pages, Paperback","First published July 31, 2003",https://www.goodreads.com/author/show/1050.Mar...,['Fiction'],"score: 55,187",591 people voted
1197,https://www.goodreads.com/book/show/4214.Life_...,18,Life of Pi,Yann Martel,Kindle Unlimited $0.00,Life of Pi is a fantasy adventure novel by Yan...,3.94,"1,665,040","54,619","592,288 (35%)","589,096 (35%)","325,216 (19%)","104,465 (6%)","53,975 (3%)","460 pages, Paperback","First published September 11, 2001",https://www.goodreads.com/author/show/811.Yann...,['Fiction'],"score: 57,891",614 people voted
1198,https://www.goodreads.com/book/show/4989.The_R...,16,The Red Tent,Anita Diamant,Kindle Unlimited $0.00,"Her name is Dinah. In the Bible, her life is o...",4.20,"609,864","22,641","293,711 (48%)","193,652 (31%)","86,216 (14%)","24,430 (4%)","11,855 (1%)","324 pages, Hardcover","First published January 1, 1997",https://www.goodreads.com/author/show/626222.A...,['Historical Fiction'],"score: 58,087",617 people voted

In [16]:
df.to_csv('data_1.csv', index=False)